#include <windows.h>
#include <stdio.h> // sprintf()

#ifndef ARRAY_SIZE
#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
#endif
#ifndef ARRAYSIZE
#define ARRAYSIZE(a) ARRAY_SIZE(s)
#endif

#ifndef WM_SETVISIBLE
#define WM_SETVISIBLE 9
#endif

static const struct {
    unsigned int type;
    const char *name;
} WinMsgNames[] = {
#undef TAB
#define TAB(x) { x, #x }
    TAB(WM_NULL),
    TAB(WM_CREATE),
    TAB(WM_DESTROY),
    TAB(WM_MOVE),
    TAB(WM_SIZE),
    TAB(WM_ACTIVATE),
    TAB(WM_SETFOCUS),
    TAB(WM_KILLFOCUS),
    TAB(WM_SETVISIBLE),
    TAB(WM_ENABLE),
    TAB(WM_SETREDRAW),
    TAB(WM_SETTEXT),
    TAB(WM_GETTEXT),
    TAB(WM_GETTEXTLENGTH),
    TAB(WM_PAINT),
    TAB(WM_CLOSE),
    TAB(WM_QUERYENDSESSION),
    TAB(WM_QUIT),
    TAB(WM_QUERYOPEN),
    TAB(WM_ERASEBKGND),
    TAB(WM_SYSCOLORCHANGE),
    TAB(WM_ENDSESSION),
    TAB(WM_SHOWWINDOW),
    TAB(WM_WININICHANGE),
    TAB(WM_DEVMODECHANGE),
    TAB(WM_ACTIVATEAPP),
    TAB(WM_FONTCHANGE),
    TAB(WM_TIMECHANGE),
    TAB(WM_CANCELMODE),
    TAB(WM_SETCURSOR),
    TAB(WM_MOUSEACTIVATE),
    TAB(WM_CHILDACTIVATE),
    TAB(WM_QUEUESYNC),
    TAB(WM_GETMINMAXINFO),
    TAB(WM_PAINTICON),
    TAB(WM_ICONERASEBKGND),
    TAB(WM_NEXTDLGCTL),
    TAB(WM_SPOOLERSTATUS),
    TAB(WM_DRAWITEM),
    TAB(WM_MEASUREITEM),
    TAB(WM_DELETEITEM),
    TAB(WM_VKEYTOITEM),
    TAB(WM_CHARTOITEM),
    TAB(WM_SETFONT),
    TAB(WM_GETFONT),
    TAB(WM_SETHOTKEY),
    TAB(WM_GETHOTKEY),
    TAB(WM_QUERYDRAGICON),
    TAB(WM_COMPAREITEM),
    TAB(WM_GETOBJECT),
    TAB(WM_COMPACTING),
    TAB(WM_COMMNOTIFY),
    TAB(WM_WINDOWPOSCHANGING),
    TAB(WM_WINDOWPOSCHANGED),
    TAB(WM_POWER),
    TAB(WM_COPYDATA),
    TAB(WM_CANCELJOURNAL),
    TAB(WM_NOTIFY),
    TAB(WM_INPUTLANGCHANGEREQUEST),
    TAB(WM_INPUTLANGCHANGE),
    TAB(WM_TCARD),
    TAB(WM_HELP),
    TAB(WM_USERCHANGED),
    TAB(WM_NOTIFYFORMAT),
    TAB(WM_CONTEXTMENU),
    TAB(WM_STYLECHANGING),
    TAB(WM_STYLECHANGED),
    TAB(WM_DISPLAYCHANGE),
    TAB(WM_GETICON),
    TAB(WM_SETICON),
    TAB(WM_NCCREATE),
    TAB(WM_NCDESTROY),
    TAB(WM_NCCALCSIZE),
    TAB(WM_NCHITTEST),
    TAB(WM_NCPAINT),
    TAB(WM_NCACTIVATE),
    TAB(WM_GETDLGCODE),
    TAB(WM_SYNCPAINT),
    TAB(WM_NCMOUSEMOVE),
    TAB(WM_NCLBUTTONDOWN),
    TAB(WM_NCLBUTTONUP),
    TAB(WM_NCLBUTTONDBLCLK),
    TAB(WM_NCRBUTTONDOWN),
    TAB(WM_NCRBUTTONUP),
    TAB(WM_NCRBUTTONDBLCLK),
    TAB(WM_NCMBUTTONDOWN),
    TAB(WM_NCMBUTTONUP),
    TAB(WM_NCMBUTTONDBLCLK),
    TAB(WM_NCXBUTTONDOWN),
    TAB(WM_NCXBUTTONUP),
    TAB(WM_NCXBUTTONDBLCLK),
    TAB(EM_GETSEL),
    TAB(EM_SETSEL),
    TAB(EM_GETRECT),
    TAB(EM_SETRECT),
    TAB(EM_SETRECTNP),
    TAB(EM_SCROLL),
    TAB(EM_LINESCROLL),
    TAB(EM_SCROLLCARET),
    TAB(EM_GETMODIFY),
    TAB(EM_SETMODIFY),
    TAB(EM_GETLINECOUNT),
    TAB(EM_LINEINDEX),
    TAB(EM_SETHANDLE),
    TAB(EM_GETHANDLE),
    TAB(EM_GETTHUMB),
    TAB(EM_LINELENGTH),
    TAB(EM_REPLACESEL),
    TAB(EM_GETLINE),
    TAB(EM_LIMITTEXT),
    TAB(EM_SETLIMITTEXT),
    TAB(EM_CANUNDO),
    TAB(EM_UNDO),
    TAB(EM_FMTLINES),
    TAB(EM_LINEFROMCHAR),
    TAB(EM_SETTABSTOPS),
    TAB(EM_SETPASSWORDCHAR),
    TAB(EM_EMPTYUNDOBUFFER),
    TAB(EM_GETFIRSTVISIBLELINE),
    TAB(EM_SETREADONLY),
    TAB(EM_SETWORDBREAKPROC),
    TAB(EM_GETWORDBREAKPROC),
    TAB(EM_GETPASSWORDCHAR),
    TAB(EM_SETMARGINS),
    TAB(EM_GETMARGINS),
    TAB(EM_GETLIMITTEXT),
    TAB(EM_POSFROMCHAR),
    TAB(EM_CHARFROMPOS),
    TAB(EM_SETIMESTATUS),
    TAB(EM_GETIMESTATUS),
    TAB(SBM_SETPOS),
    TAB(SBM_GETPOS),
    TAB(SBM_SETRANGE),
    TAB(SBM_GETRANGE),
    TAB(SBM_ENABLE_ARROWS),
    TAB(SBM_SETRANGEREDRAW),
    TAB(SBM_SETSCROLLINFO),
    TAB(SBM_GETSCROLLINFO),
    TAB(SBM_GETSCROLLBARINFO),
    TAB(BM_GETCHECK),
    TAB(BM_SETCHECK),
    TAB(BM_GETSTATE),
    TAB(BM_SETSTATE),
    TAB(BM_SETSTYLE),
    TAB(BM_CLICK),
    TAB(BM_GETIMAGE),
    TAB(BM_SETIMAGE),
    TAB(WM_INPUT),
    TAB(WM_KEYDOWN),
    TAB(WM_KEYUP),
    TAB(WM_CHAR),
    TAB(WM_DEADCHAR),
    TAB(WM_SYSKEYDOWN),
    TAB(WM_SYSKEYUP),
    TAB(WM_SYSCHAR),
    TAB(WM_SYSDEADCHAR),
    TAB(WM_UNICHAR),
    TAB(WM_IME_STARTCOMPOSITION),
    TAB(WM_IME_ENDCOMPOSITION),
    TAB(WM_IME_COMPOSITION),
    TAB(WM_INITDIALOG),
    TAB(WM_COMMAND),
    TAB(WM_SYSCOMMAND),
    TAB(WM_TIMER),
    TAB(WM_HSCROLL),
    TAB(WM_VSCROLL),
    TAB(WM_INITMENU),
    TAB(WM_INITMENUPOPUP),
    TAB(WM_MENUSELECT),
    TAB(WM_MENUCHAR),
    TAB(WM_ENTERIDLE),
    TAB(WM_MENURBUTTONUP),
    TAB(WM_MENUDRAG),
    TAB(WM_MENUGETOBJECT),
    TAB(WM_UNINITMENUPOPUP),
    TAB(WM_MENUCOMMAND),
    TAB(WM_CHANGEUISTATE),
    TAB(WM_UPDATEUISTATE),
    TAB(WM_QUERYUISTATE),
    TAB(WM_CTLCOLORMSGBOX),
    TAB(WM_CTLCOLOREDIT),
    TAB(WM_CTLCOLORLISTBOX),
    TAB(WM_CTLCOLORBTN),
    TAB(WM_CTLCOLORDLG),
    TAB(WM_CTLCOLORSCROLLBAR),
    TAB(WM_CTLCOLORSTATIC),
    TAB(WM_MOUSEMOVE),
    TAB(WM_LBUTTONDOWN),
    TAB(WM_LBUTTONUP),
    TAB(WM_LBUTTONDBLCLK),
    TAB(WM_RBUTTONDOWN),
    TAB(WM_RBUTTONUP),
    TAB(WM_RBUTTONDBLCLK),
    TAB(WM_MBUTTONDOWN),
    TAB(WM_MBUTTONUP),
    TAB(WM_MBUTTONDBLCLK),
    TAB(WM_MOUSEWHEEL),
    TAB(WM_XBUTTONDOWN),
    TAB(WM_XBUTTONUP),
    TAB(WM_XBUTTONDBLCLK),
    TAB(WM_PARENTNOTIFY),
    TAB(WM_ENTERMENULOOP),
    TAB(WM_EXITMENULOOP),
    TAB(WM_NEXTMENU),
    TAB(WM_SIZING),
    TAB(WM_CAPTURECHANGED),
    TAB(WM_MOVING),
    TAB(WM_POWERBROADCAST),
    TAB(WM_DEVICECHANGE),
    TAB(WM_MDICREATE),
    TAB(WM_MDIDESTROY),
    TAB(WM_MDIACTIVATE),
    TAB(WM_MDIRESTORE),
    TAB(WM_MDINEXT),
    TAB(WM_MDIMAXIMIZE),
    TAB(WM_MDITILE),
    TAB(WM_MDICASCADE),
    TAB(WM_MDIICONARRANGE),
    TAB(WM_MDIGETACTIVE),
    TAB(WM_MDISETMENU),
    TAB(WM_ENTERSIZEMOVE),
    TAB(WM_EXITSIZEMOVE),
    TAB(WM_DROPFILES),
    TAB(WM_MDIREFRESHMENU),
    TAB(WM_IME_SETCONTEXT),
    TAB(WM_IME_NOTIFY),
    TAB(WM_IME_CONTROL),
    TAB(WM_IME_COMPOSITIONFULL),
    TAB(WM_IME_SELECT),
    TAB(WM_IME_CHAR),
    TAB(WM_IME_REQUEST),
    TAB(WM_IME_KEYDOWN),
    TAB(WM_IME_KEYUP),
    TAB(WM_NCMOUSEHOVER),
    TAB(WM_MOUSEHOVER),
    TAB(WM_NCMOUSELEAVE),
    TAB(WM_MOUSELEAVE),
    TAB(WM_CUT),
    TAB(WM_COPY),
    TAB(WM_PASTE),
    TAB(WM_CLEAR),
    TAB(WM_UNDO),
    TAB(WM_RENDERFORMAT),
    TAB(WM_RENDERALLFORMATS),
    TAB(WM_DESTROYCLIPBOARD),
    TAB(WM_DRAWCLIPBOARD),
    TAB(WM_PAINTCLIPBOARD),
    TAB(WM_VSCROLLCLIPBOARD),
    TAB(WM_SIZECLIPBOARD),
    TAB(WM_ASKCBFORMATNAME),
    TAB(WM_CHANGECBCHAIN),
    TAB(WM_HSCROLLCLIPBOARD),
    TAB(WM_QUERYNEWPALETTE),
    TAB(WM_PALETTEISCHANGING),
    TAB(WM_PALETTECHANGED),
    TAB(WM_HOTKEY),
    TAB(WM_PRINT),
    TAB(WM_PRINTCLIENT),
    TAB(WM_APPCOMMAND),
    TAB(WM_HANDHELDFIRST),
    TAB(WM_HANDHELDLAST),
    TAB(WM_AFXFIRST),
    TAB(WM_AFXLAST),
    TAB(WM_PENWINFIRST),
    TAB(WM_PENWINLAST),
    TAB(WM_USER),
    TAB(NIN_SELECT),
    TAB(WM_PSD_PAGESETUPDLG),
    TAB(WM_USER),
    TAB(DM_SETDEFID),
    TAB(WM_CHOOSEFONT_GETLOGFONT),
    TAB(WM_PSD_FULLPAGERECT),
    TAB(DM_REPOSITION),
    TAB(WM_PSD_MINMARGINRECT),
    TAB(WM_PSD_MARGINRECT),
    TAB(WM_PSD_GREEKTEXTRECT),
    TAB(WM_PSD_ENVSTAMPRECT),
    TAB(WM_PSD_YAFULLPAGERECT),
    TAB(CDM_FIRST),
    TAB(CDM_GETSPEC),
    TAB(CDM_GETFILEPATH),
    TAB(PSM_SETCURSEL),
    TAB(WM_CHOOSEFONT_SETLOGFONT),
    TAB(CDM_GETFOLDERPATH),
    TAB(PSM_REMOVEPAGE),
    TAB(WM_CHOOSEFONT_SETFLAGS),
    TAB(CDM_GETFOLDERIDLIST),
    TAB(PSM_ADDPAGE),
    TAB(CDM_SETCONTROLTEXT),
    TAB(PSM_CHANGED),
    TAB(CDM_HIDECONTROL),
    TAB(PSM_RESTARTWINDOWS),
    TAB(CDM_SETDEFEXT),
    TAB(PSM_REBOOTSYSTEM),
    TAB(PSM_CANCELTOCLOSE),
    TAB(PSM_QUERYSIBLINGS),
    TAB(PSM_UNCHANGED),
    TAB(PSM_APPLY),
    TAB(PSM_SETTITLEA),
    TAB(PSM_SETWIZBUTTONS),
    TAB(PSM_PRESSBUTTON),
    TAB(PSM_SETCURSELID),
    TAB(PSM_SETFINISHTEXTA),
    TAB(PSM_GETTABCONTROL),
    TAB(PSM_ISDIALOGMESSAGE),
    TAB(PSM_GETCURRENTPAGEHWND),
    TAB(PSM_INSERTPAGE),
    TAB(PSM_SETTITLEW),
    TAB(PSM_SETFINISHTEXTW),
    TAB(PSM_SETHEADERTITLEA),
    TAB(PSM_SETHEADERTITLEW),
    TAB(PSM_SETHEADERSUBTITLEA),
    TAB(PSM_SETHEADERSUBTITLEW),
    TAB(PSM_HWNDTOINDEX),
    TAB(PSM_INDEXTOHWND),
    TAB(PSM_PAGETOINDEX),
    TAB(PSM_INDEXTOPAGE),
    TAB(PSM_IDTOINDEX),
    TAB(PSM_INDEXTOID),
    TAB(PSM_GETRESULT),
    TAB(PSM_RECALCPAGESIZES),
    TAB(CDM_LAST),
    TAB(WM_APP),
    /*
    For messages in the WM_USER..0x7FFF range, it might be worth returning a
    string in WM_USER+X format, which could help a user track down the
    message definition in source code. Same with the WM_APP...0xBFFF range.
    As for messages in the 0xC000..0xFFFF, you can currently use
    GetClipboardFormatName() to get its name (MAY change in the future,
    though!).
    */
#undef TAB
};

const char *debWin_msg(UINT uMsg)
{
    const int maxAtomSize = 256; // see AddAtom() documentation
    static char buf[4096] = { };
    static char *bufp = buf;

    for (size_t i = 0; i < ARRAY_SIZE(WinMsgNames); i++)
        if (WinMsgNames[i].type == uMsg)
            return WinMsgNames[i].name;

    // wrap around
    if (bufp + maxAtomSize > buf + sizeof(buf)) bufp = buf;

    if (UINT len = GlobalGetAtomName(uMsg, bufp, maxAtomSize)) {
        char *p = bufp; p[len] = '\0';
        bufp += len + 1;
        return p;
    }
    if (UINT len = GetAtomName(uMsg, buf, sizeof(buf)-1)) {
        char *p = bufp; p[len] = '\0';
        bufp += len + 1;
        return p;
    }
    int len = sprintf(bufp, "MsgUnknown(%u)", uMsg);
    char *p = bufp;
    bufp += len + 1;
    return p;
}

//
// gettimeofday()
//

struct Timer
{
    Timer()
    {
        LARGE_INTEGER largeFreq;
        QueryPerformanceFrequency(&largeFreq);
        freq = largeFreq.QuadPart;
    }

    __int64 GetCount()
    {
        LARGE_INTEGER count;
        QueryPerformanceCounter(&count);
        return count.QuadPart;
    }

    // returns number of ms between 2 counts
    double CalcTimeDelta(__int64 count1, __int64 count2)
    {
        return ((double)count2/(double)freq - (double)count1/(double)freq) * 1000.0;
    }

private:
    // num. counts per second
    __int64 freq;
};
